# Generated by Django 2.2 on 2019-04-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200, verbose_name='نام')),
                ('l_name', models.CharField(max_length=250, verbose_name='نام خانوادگی')),
                ('meliyat', models.CharField(choices=[('IR', 'ایرانی'), ('AF', 'افغانی')], max_length=2, verbose_name='ملیت')),
                ('vaziyet_kari', models.CharField(choices=[('krg', 'کارگر'), ('ost', 'استادکار')], max_length=3, verbose_name='وضعیت کاری')),
            ],
        ),
    ]
