# Generated by Django 2.2 on 2019-04-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kagar',
            new_name='kagare',
        ),
    ]
