# Generated by Django 2.2 on 2019-04-08 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190408_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='reshte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reshte_name', models.CharField(max_length=200)),
            ],
        ),
    ]
