# Generated by Django 2.2 on 2019-04-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_reshte'),
    ]

    operations = [
        migrations.CreateModel(
            name='personel_cyrus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200, verbose_name='نام')),
                ('l_name', models.CharField(max_length=250, verbose_name='نام خانوادگی')),
                ('meli_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('celphone_one', models.CharField(help_text='لطفا شماره تلفن همراه را در این حالت وارد کنید 09113910400', max_length=11, verbose_name='شماره تلفن همراه')),
                ('tel_sabet', models.CharField(max_length=11, verbose_name='شماره تلفن ثابت')),
                ('maghtae_tahsili', models.CharField(choices=[('ci', 'سیکل'), ('dp', 'دیپلم'), ('fd', 'فوق دیپلم'), ('li', 'لیسانس'), ('fl', 'فوف لیسانس'), ('dr', 'دکترا')], default='dp', max_length=2, verbose_name='مقطع تحصیلی')),
                ('reshte_tahsili', models.ForeignKey(on_delete='رشته تحصیلی', to='web.reshte')),
            ],
        ),
    ]
