# Generated by Django 2.2 on 2019-04-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_personel_cyrus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel_cyrus',
            name='address',
            field=models.CharField(max_length=300, verbose_name='آدرس'),
        ),
    ]
