# Generated by Django 2.2 on 2019-04-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190408_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_cyrus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=50, verbose_name='نام پروژه')),
                ('address_project', models.CharField(max_length=300, verbose_name='آدرس پروژه')),
                ('units_project', models.CharField(max_length=2, verbose_name='تعداد واحد ها')),
                ('desc_project', models.TextField(verbose_name='توضیحات تکمیلی')),
            ],
        ),
    ]
