# Generated by Django 2.2 on 2019-04-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_project_cyrus'),
    ]

    operations = [
        migrations.AddField(
            model_name='kagar_cyrus',
            name='moaref_kargar',
            field=models.ForeignKey(null=True, on_delete='معرف', to='web.personel_cyrus'),
        ),
    ]
