# Generated by Django 2.2 on 2019-04-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20190409_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel_cyrus',
            name='semat',
            field=models.CharField(blank=True, choices=[('modir_project', 'مدیر پروژه'), ('mohandes', 'مهندس '), ('ranande', 'راننده'), ('modir_hesabdar', 'مدیر حسابداری'), ('anbardar', 'انباردار'), ('tarrah', 'معمار پروژه'), ('monshi', 'منشی'), ('vakil', 'وکیل')], help_text='سمت را در این قسمت انتخاب کنید', max_length=50, null=True, verbose_name=''),
        ),
    ]
