# Generated by Django 2.2 on 2019-04-11 05:40

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_personel_cyrus_semat'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel_cyrus',
            name='birth_day',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='personel_cyrus',
            name='semat',
            field=models.CharField(blank=True, choices=[('modir_project', 'مدیر پروژه'), ('mohandes', 'مهندس '), ('ranande', 'راننده'), ('modir_hesabdar', 'مدیر حسابداری'), ('anbardar', 'انباردار'), ('tarrah', 'معمار پروژه'), ('monshi', 'منشی'), ('vakil', 'وکیل')], help_text='سمت را در این قسمت انتخاب کنید', max_length=50, null=True, verbose_name='سمت در پروژه'),
        ),
    ]
