# Generated by Django 2.2 on 2019-04-11 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0013_auto_20190410_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='kagar_cyrus',
            name='birthday',
            field=django_jalali.db.models.jDateField(blank=True, help_text='تاریخ تولد را وارد کنید', null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='kagar_cyrus',
            name='meli_code',
            field=models.CharField(blank=True, help_text='ورود کد ملی ۱۰ رقمی', max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.CreateModel(
            name='karkard_cyrus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikh', django_jalali.db.models.jDateField(help_text='تاریخ روز کاری مورد نظر را مشخص کنید', verbose_name='تاریخ')),
                ('sharh', models.CharField(help_text='شرح فعالیت روزانه را در این قسمت بنویسید', max_length=500, verbose_name='شرح فعالیت امروز')),
                ('kargar', models.ForeignKey(help_text='کارگر مورد نظر را با دقت انتخاب کنید', on_delete=django.db.models.deletion.DO_NOTHING, to='web.kagar_cyrus')),
                ('project', models.ForeignKey(help_text='پروژه مورد نظر را انتخاب کنید', on_delete=django.db.models.deletion.DO_NOTHING, to='web.project_cyrus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
