# Generated by Django 2.2 on 2019-04-11 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0014_auto_20190410_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='sabteruz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikh', django_jalali.db.models.jDateField(help_text='تاریخ روز کاری مورد نظر را مشخص کنید', verbose_name='تاریخ')),
                ('project', models.ForeignKey(help_text='پروژه مورد نظر را انتخاب کنید', on_delete=django.db.models.deletion.DO_NOTHING, to='web.project_cyrus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
