# Generated by Django 2.2 on 2019-04-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20190411_0017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='karkard_cyrus',
        ),
    ]
