# Generated by Django 2.2 on 2019-04-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_delete_karkard_cyrus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabteruz',
            name='dsc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
