# Generated by Django 2.2 on 2019-04-22 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20190411_0050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karkard',
            options={'verbose_name': 'ثبت کارکرد', 'verbose_name_plural': 'لیست کارکرد ها'},
        ),
        migrations.AlterField(
            model_name='sabteruz',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
