# Generated by Django 2.2 on 2019-04-22 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20190422_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sabteruz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
