# Generated by Django 2.2 on 2019-04-26 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20190422_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sabteruz',
            name='user',
            field=models.ForeignKey(help_text='در این قسمت نام کاربری خود را انتخاب کنید', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
